server:
  port: 9001
  tomcat:
    connection-timeout: 3s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  datasource:
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/vinyls_catalog
    hikari:
      connection-timeout: 2000 #ms
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

